# PostgreSQL:
version: '3.7'
services:
  postgres:
    image: postgres:12
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=default
      - POSTGRES_DB=default

  pgadmin:
    container_name: pgadmin4-test-rest
    image: dpage/pgadmin4:4.10
    depends_on:
    - postgres
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=temporary@test.com
      - PGADMIN_DEFAULT_PASSWORD=tempPass
    volumes:
      - ./servers.json:/pgadmin4/servers.json

# MySQL equivalent:
# version: '3.1'

# services:

#   db:
#     image: mysql:5.7
#     command: --default-authentication-plugin=mysql_native_password
#     restart: always
#     ports:
#       - "8001:3306"
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: test
#       MYSQL_PASSWORD: example

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080