#This is an example configuration

port: 8080
verbose: true
jsonFormatter: false
shutdownTimeout: 15
dbType: "postgres"
dbName: "postgres"
dbUser: "default"
dbPassword: "default"
dbSslMode: "disable"
dbHost: "localhost"
dbPort: 5432